/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData user = IconData(0xf007, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xf015, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_medical = IconData(0xf477, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_medical_alt = IconData(0xf478, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData first_aid = IconData(0xf479, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital_alt = IconData(0xf47d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital_symbol = IconData(0xf47e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_card_alt = IconData(0xf47f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notes_medical = IconData(0xf481, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pills = IconData(0xf484, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prescription_bottle = IconData(0xf485, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prescription_bottle_alt = IconData(0xf486, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData syringe = IconData(0xf48e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablets = IconData(0xf490, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer = IconData(0xf491, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vial = IconData(0xf492, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vials = IconData(0xf493, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_plus = IconData(0xf65e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clinic_medical = IconData(0xf7f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
